typography_spectrum: 0.8037127517163754
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5163467691745609
  lightness: 0.7050397095736116
  saturation: 0.21213713753968477
  rhythmicContrast: 0.3361008446663618
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1157626355998218
analytics:
  google: null
  facebook: null
  twitter: null
name: simplyhealth4u
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: >-
      Let us show you how to optimize your health, help the environment and save
      time & money. We are also looking for qualified individuals for unique
      opportunities to start their own businesses.
    url: 'http://amway.ca/simplyhealth4u'
    type: external
favicon: null
purpose: []
